OTT-1889: Agent table-level statistics scheduling framework
ottertune/ot-agent pull request #49
Opened 2022-03-28 18:11 UTC by YuzeLiao

2022-03-29 00:57 UTC, bohanjason requested changes
I think we should implement it in driver first.

2022-03-29 00:57 UTC, bohanjason commented on driver/collector/base_collector.py
> +    def collect_table_level_metrics(self, num_table_to_collect_stas: int) -> Dict[str, Any]:
```suggestion
    def collect_table_level_metrics(self, num_table_to_collect_stats: int) -> Dict[str, Any]:
```

2022-03-29 00:57 UTC, bohanjason commented on driver/collector/postgres_collector.py
> +                        "to_do",
```suggestion
                        "a", "b", "c",
```

2022-03-29 00:57 UTC, bohanjason commented on driver/collector/mysql_collector.py
> +                        "mysql_to_implement",
```suggestion
                        "a", "b", "c",
```

2022-04-04 16:33 UTC, ruogudu commented on driver/compute_server_client.py
> +        """url = f"{self._server_url}/observation/"
Is this still a draft? Also the URL should be difference.

2022-04-15 16:06 UTC, ruogudu approved these changes

2022-05-04 18:25 UTC, bohanjason requested changes

2022-05-04 19:29 UTC, bohanjason approved these changes

2022-05-04 19:29 UTC, merged